### ISSUE TITLE
Availability of lmb=1024 for qres17m model

### ISSUE THREAD

**Issue by qiutiantxwd** [duanzhiihao/lossy-vae#17]
Hi Zhihao,
Thanks for sharing this great codebase.
Is the checkpoint for lambda=1024 for the qres17m model available to download? I saw it was mentioned in Fig. 5(a) of the paper, but not available for download. 
Thanks!

**Comment by duanzhiihao** [comment]
Hi Tian, thanks for your interest in our work!
lambda = 1024 for the qres17m model was actually a typo in the [camera-ready paper](https://openaccess.thecvf.com/content/WACV2023/papers/Duan_Lossy_Image_Compression_With_Quantized_Hierarchical_VAEs_WACV_2023_paper.pdf). It should be lambda = 64. I later fixed this typo in the arxiv version of the paper (https://arxiv.org/abs/2208.13056). Please refer to the arxiv version if possible. Sorry for causing the confusion.

**Comment by qiutiantxwd** [comment]
Thanks for the correction, that makes lots of sense!
